version: '2'

networks:
  web:
    external: true
  internal:
    external: false


services:
  db:
    container_name: proficiencia_db
    image: postgres:9.6.11
    ports:
      - 5533:5432
    environment:
      - POSTGRES_USER=${PROFICIENCIA_USER}
      - POSTGRES_PASSWORD=${PROFICIENCIA_PASSWORD}
      - POSTGRES_DB=${PROFICIENCIA_DB}
    volumes:
      - /opt/sistemas/sigaep/data:/var/lib/postgresql/data
      - ./app/db/script.sql:/docker-entrypoint-initdb.d/script.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
      - web


  back:
    container_name: proficiencia_back
    image: tomcat:9.0.12-jre8
    depends_on:
      - db
    environment:
      - CATALINA_OPTS=-DPROFICIENCIA_USER=${PROFICIENCIA_USER} -DPROFICIENCIA_PASSWORD=${PROFICIENCIA_PASSWORD} -DPROFICIENCIA_URL=${PROFICIENCIA_URL}
    volumes:
      - ./proficiencia/back-end/target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./proficiencia/back-end/target/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./app/conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ./app/conf/web.xml:/usr/local/tomcat/conf/web.xml
      - ./app/lib/javax.mail.jar:/usr/local/tomcat/lib/javax.mail.jar
      - ./app/lib/postgresql-42.2.6.jar:/usr/local/tomcat/lib/postgresql-42.2.6.jar
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=back"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:sigaep.quixada.ufc.br; PathPrefixStrip: /api"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.default.protocol=http"
    networks:
      - internal
      - web

  front:
    container_name: proficiencia_front
    image: nginx:1.17-alpine
    depends_on:
      - back
    volumes:
      - ./app/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proficiencia/front-end/dist:/usr/share/nginx/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=front"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:sigaep.quixada.ufc.br"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    networks:
      - internal
      - web